### ISSUE TITLE
Plugin doesn't work with Django 1.7

### ISSUE THREAD

**Issue by mrsarm** [aldryn/aldryn-news#42]
I have installed with pip the plugin, and added it to settings.py, but when I run ``python manage.py migrate``, I get this error:

    TypeError: Couldn't reconstruct m2m field tags on News: __init__() got an unexpected keyword argument 'serialize'

Does the plugin works with Django 1.7 and the new "Migration" system?

I have my virtualenv with Python 2.7 and:

* Django==1.7.1
* django-cms==3.0.7
* aldryn-news==0.1.16

**Comment by kelvan** [comment]
I had the same error, but it seems it was not the fault of aldryn-news itself.
I used old django-taggit 0.11 (installed as dependency of aldryn-news?)
upgraded to 0.12, disabled news, migrate, enabled news, migrate again, worked

(also forked aldryn-news to workaround FieldDoesNotExist error)

**Comment by GooeyGungan** [comment]
@kelvan 's solution fixed it for me as well, though I only updated to 0.14 and did none of the other things suggested.
